#!/bin/python

import sys

passwd="/etc/passwd"

users={}

with open(passwd,"r") as f:
    for line in f:
        user=line.strip('\n').split(':')
        users[user[0]]={
            "password":user[1],
            "uid":user[2],
            "gid":user[3],
            "comment":user[4],
            "dir":user[5],
            "shell":user[6]
        }

try:
    if len(sys.argv)<=1:
        for name in users:
            print(name)
    elif len(sys.argv)==2:
        for field in users[sys.argv[1]]:
            print("%s:%s"%(field,users[sys.argv[1]][field]))
    elif len(sys.argv)==3:
        print(users[sys.argv[1]][sys.argv[2]])
except KeyError as e:
    print("Invalid argument "+e.args[0],file=sys.stderr)
